#%RAML 1.0 DataType
type: object
properties:
  Amount:
    type: string
    required: true
  CostType:
    type: string
    required: false
  PublicID:
    type: string
    required: true
  RecoveryCategory:
    type: string
    required: false